### ISSUE TITLE
whitespace issues?

### ISSUE THREAD

**Issue by mvolkmann** [algolia/expect-jsx#14]
This seems to have problems when an element contains multiple JavaScript expressions and literal text. For example, I have a component that renders this JSX:

<div>
  {this.getUncompletedCount(iTodos)} of {iTodos.size} remaining
</div>

I'm trying to test it with this:

expect(output).toEqualJSX(
  <div>1 of 2 remaining</div>
);

The test fails with this output:
      + expected - actual

         <div>
      -    1
      -     of
      -    2
      -     remaining
      +    1 of 2 remaining
         </div>

Note how the actual value contains several newline characters (not sure why) and the expected value does not. Could it be that React always adds a newline after rendering expressions in braces?

**Comment by vvo** [comment]
Hi @mvolkmann, could you please open a bug on https://github.com/algolia/react-element-to-jsx-string with a new test case? It's as easy as adding a new entry to https://github.com/algolia/react-element-to-jsx-string/blob/master/index-test.js.

Let me know

**Comment by smacker** [comment]
I had this problem too, but I thought it's feature, not a bug. I added test and fix, but right now my tests depend on current behavior with a new line.

**Comment by vvo** [comment]
was fixed and released
