### ISSUE TITLE
Add toNotEqualJSX

### ISSUE THREAD

**Issue by mjackson** [algolia/expect-jsx#2]
We should probably have a `toNotEqualJSX` method as well, since all our other assertions have a `toNot*` equivalent.

EDIT: If you decide to export a single object with all your assertions, as [I suggested here](https://github.com/mjackson/expect/issues/37#issuecomment-148612089) then users would be able to get both `toEqualJSX` *and* `toNotEqualJSX` with just `expect.extend(require('expect-jsx'))`. :)

**Comment by rstacruz** [comment]
also, `toIncludeJSX` might be cool too:

```js
function renderCounter (count) {
  return <div><span>{count}</span></div>;
}
```

```js
expect(renderCounter(90)).toIncludeJSX(<span>90</span>)
```

**Comment by vvo** [comment]
I was about to say this, both of them are really easy to add. I will do all the changes. Thanks for the ideas!
