### ISSUE TITLE
Please publish a new version on npm

### ISSUE THREAD

**Issue by okuryu** [algolia/expect-jsx#28]
The #27 is not available on npm. Could you publish a new version for this?

**Comment by Haroenv** [comment]
published as 3.1.0

@vvo, our new security policy prevents me from pushing to master, how do we get around publishing with our script?

**Comment by vvo** [comment]
@Haroenv Do you mean git push origin master did not work? Or are you wondering if that's ok security wise?

**Comment by vvo** [comment]
This is a public repository, with no production system behind it, not directly related to algolia (but having been developed on my Algolia time). So it's safe completely to push updates to master and npm. Go

**Comment by vvo** [comment]
We only need to be more flexible on this repository as for releasing new versions. Easiest would be to have release scripts that make travis pass.

**Comment by vvo** [comment]
Also this is a major update that we should be doing since we updated react-element-jsx-string (that's what I do most of the time)

**Comment by vvo** [comment]
Released v4

**Comment by Haroenv** [comment]
Oops, you're right!

**Comment by vvo** [comment]
No prob
