### ISSUE TITLE
Link to chai plugin

### ISSUE THREAD

**Issue by epsitec** [algolia/expect-jsx#9]
An equivalent plugin for the **chai** framework is available as [chai-equal-jsx](https://github.com/echenley/chai-equal-jsx). It is using `react-element-to-jsx-string` under the Hood and exports `equalJSX` and `includeJSX`. You might want to provide a reference to it.

**Comment by vvo** [comment]
@epsitec Works for me, send in a pull request Ill merge it.

There's also
https://www.npmjs.com/package/chai-equal-jsx
https://www.npmjs.com/package/chai-jsx
https://www.npmjs.com/package/tape-jsx-equals

all built on react-element-to-jsx-string

**Comment by vvo** [comment]
was merged
